cd /d C:\RL_automate
Start py RL-arg.py "August 4"
Start py RL-arg.py "August 5"
Start py RL-arg.py "August 8"
Start py RL-arg.py "August 9"
Start py RL-arg.py "August 10"
Start py RL-arg.py "August 11"
Start py RL-arg.py "August 12"
Start py RL-arg.py "August 16"
Start py RL-arg.py "August 17"
Start py RL-arg.py "August 18"
Start py RL-arg.py "August 19"
Start py RL-arg.py "August 22"
Start py RL-arg.py "August 23"
Start py RL-arg.py "August 24"
Start py RL-arg.py "August 25"
Start py RL-arg.py "August 26"
Start py RL-arg.py "August 29"
Start py RL-arg.py "August 30"



